# -*- coding: utf-8 -*-
"""Merge Sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGjC-hVyxIQppHWVtYyuBeAOjEwhir0o
"""

step_count = 0

def merge(ordArrIzq, ordArrDer):
    global step_count
    arrResul = []
    while len(ordArrIzq) > 0 and len(ordArrDer) > 0:
        step_count += 1
        if ordArrIzq[0] < ordArrDer[0]:
            arrResul.append(ordArrIzq[0])
            ordArrIzq.pop(0)
        else:
            arrResul.append(ordArrDer[0])
            ordArrDer.pop(0)

    while len(ordArrIzq) > 0:
        step_count += 1
        arrResul.append(ordArrIzq[0])
        ordArrIzq.pop(0)

    while len(ordArrDer) > 0:
        step_count += 1
        arrResul.append(ordArrDer[0])
        ordArrDer.pop(0)

    return arrResul

def mergeSort(arr):
    global step_count
    if len(arr) == 1:
        return arr
    mitad = len(arr) // 2
    arrIzq = arr[:mitad]
    arrDer = arr[mitad:]
    ordArrIzq = mergeSort(arrIzq)
    ordArrDer = mergeSort(arrDer)
    return merge(ordArrIzq, ordArrDer)

def generate_descending_arrays():
    array_100 = list(range(100, 0, -1))
    array_1000 = list(range(1000, 0, -1))
    array_10000 = list(range(10000, 0, -1))

    return array_100, array_1000, array_10000

arr_100, arr_1000, arr_10000 = generate_descending_arrays()

step_count = 0
mergeSort(arr_100)
print(f"Numero de pasos para un arreglo de 100 elementos: {step_count}")

step_count = 0
mergeSort(arr_1000)
print(f"Numero de pasos para un arreglo de 1000 elementos: {step_count}")

step_count = 0
mergeSort(arr_10000)
print(f"Numero de pasos para un arreglo de 10000 elementos: {step_count}")